[package]
name = "beast"
version = "0.1.0"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]

[dependencies]
pest = "1.0.6"
pest_derive = "1.0.7"
serde = "1.0.37"
serde_derive = "1.0.37"
melon = "0.7.0"
toml = "0.4.5"
failure = "0.1.1"
flate2 = "1.0.1"
rmp-serde = "0.13.7"
