[package]
name = "beast"
version = "0.1.0"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]

[dependencies]
pest = "1.0.6"
pest_derive = "1.0.6"
serde = "1.0.36"
serde_derive = "1.0.36"
melon = "0.5.1"
toml = "0.4.5"
failure = "0.1.1"
