# This is a configuration file template

[program]
name = "program_name"
target_version = "0.8.0" # the version of the melon library used by the target
system_id = "__DEBUG__"

# [signals]
# gurgle = 1
# nuke = 2
# fire = 3
